# pylint: disable-all
"""Used approved state

Revision ID: 4d6c04a12401
Revises:
Create Date: 2022-01-20 16:31:48.067813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6c04a12401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade revision part."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('first_name', sa.String(length=200), nullable=True),
        sa.Column('last_name', sa.String(length=200), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'APPROVER', 'COMPLAINER', name='roletype'),
            server_default='COMPLAINER',
            nullable=False,
        ),
        sa.Column(
            'iban',
            sa.String(length=200),
            server_default='COMPLAINER',
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'complaints',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('photo_url', sa.String(length=200), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column(
            'status',
            sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='state'),
            server_default='PENDING',
            nullable=False,
        ),
        sa.Column('complainer_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['complainer_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revision part."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    op.drop_table('users')
    # ### end Alembic commands ###
