# pylint: disable-all
"""Add transaction table

Revision ID: a4f8eb0b59de
Revises: 4d6c04a12401
Create Date: 2022-01-21 22:05:23.897144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f8eb0b59de'
down_revision = '4d6c04a12401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade revision part."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quote_id', sa.String(length=120), nullable=False),
        sa.Column('transfer_id', sa.Integer(), nullable=False),
        sa.Column('target_account_id', sa.String(length=120), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('complaint_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['complaint_id'],
            ['complaints.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revision part."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
