version: "3.7"

services:
  db:
    image: vyahello/complainer-db:0.1.0
    ports:
      - "5434:5432"

  back:
    image: vyahello/complainer-back:0.1.0
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    image: vyahello/complainer-front:0.1.0
    ports:
      - "4200:4200"
    depends_on:
      - back
